config/routes.rb
Rails.application.routes.draw do
  root to: "articles#index"
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:success] = "Article has been created"
      redirect_to articles_path
    else
      flash.now[:danger] = "Article has not been created"
      render :new
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/index.html.erb
<%= link_to 'New Article', new_article_path, class: "btn btn-default btn-lg", id: "new-article-btn" %>

app/views/articles/new.html.erb
<h3 class="text-center">Add New Article</h3>

<div class="row">
  <div class="col-md-12">
    <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <% if @article.errors.any? %>
        <div class="panel panel-danger col-md-offset-1">
          <div class="panel-heading">
            <h2 class="panel-title">
              <%= pluralize(@article.errors.count, "error") %>
              prohibited this article from being created:
            </h2>

            <div class="panel-body">
              <ul>
              <% @article.errors.full_messages.each do |msg| %>
                <li>
                  <%= msg %>
                </li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>

      <% end %>
      <div class="form-group">
        <div class="control-label col-md-1">
          <%= f.label :title %>
        </div>
        <div class="col-md-8">
          <%= f.text_field :title, class: 'form-control', placeholder: "Title of Article", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-md-1">
          <%= f.label :body %>
        </div>
        <div class="col-md-8">
          <%= f.text_area :body, rows: 10, class: 'form-control', placeholder: "Body of Article" %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-md-offset-1 col-md-8">
          <%= f.submit class: "btn btn-primary btn-lg pull-right" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <title>BlogApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header role="banner">
      <ul class="nav nav-tabs">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Active</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Dropdown</a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Separated link</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
    </header>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <% flash.each do |key, message| %>
            <div class="text-center alert alert-<%= key == 'notice'? 'success': 'danger' %>">
              <%= message %>
            </div>
          <% end %>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>